### ISSUE TITLE
Glosario de Ética y Deontología Profesional

### ISSUE THREAD

**Issue by SofiaEJac** [SofiaEJac/Grupo5A17_Programador2022#3]

**Comment by lacman92** [comment]
[Ejercicio profesional_Material complementario_Proactividad.pdf](https://github.com/SofiaEJac/Grupo5A17_Programador2022/files/9002220/Ejercicio.profesional_Material.complementario_Proactividad.pdf)

Adjunto PDF con la guia completa de estudio sobre ETICA Y DEONTOLOGIA PROFESIONAL

**Comment by SofiaEJac** [comment]
**Conceptos sobre el dilema en las redes sociales**
_Desplazamiento automático_: estrategia desarrollada para que la experiencia de red no tenga fin y el usuario permanezca conectado. Establece una carga automático de contenido (fotos, publicaciones, artículos o videos) a medida que el usuario va deslizando sus dedos y ojos por la pantalla. 
_Estrategias digitales para generar adicción a las redes sociales_: recomendaciones automáticas, notificaciones y publicaciones sugeridas. El objetivo es acaparar el tiempo de las personas, una moneda valiosa para empresas,
políticos, organizaciones o países que quieran vender productos o ideas a audiencias vulnerables e hipersegmentadas.
_Sistemas de recompensa inmediata_: las redes sociales han creado métodos de navegación que a través de los "me gusta" o interacciones positivas online (comentarios, seguidores, etc.) disparan nuevos impulsos artificiales de dopamina, manteniendo la conexión de los usuarios más tiempo.
_Noticias falsas_:  la información falsa tiene un gran alcance en las redes sociales debido a "la paranoia" de mantener a los usuarios expuestos continuamente a los anuncios, generando así ganancias para las empresas.
 
**Consejos para protegerse**:
1. Deshabilitar las notificaciones para tener mayor control sobre el acceso a las redes.
2. No dejarse llevar por las recomendaciones de contenidos sin reflexionar.
3. Sigue a personas y páginas que no estén necesariamente alineadas con tu pensamiento, 
4. Propicia la desconexión total al menos 1 hora antes de dormir.
5. Valora tus clics y tu tiempo. Recuerda que de acuerdo a tu forma de relacionarte con los contenidos, las empresas ganan dinero.

**Comment by YESS-BAIT-LEJEM** [comment]
**### _Conceptos sobre ética y moral_**

¿Qué es la Ética?:

Étimología del griego _ETHOS_ manera de hacer- Aristóteles. 

1. Es la busqueda del bien, a través de una relación armoniosa respecto a la realización personal con los demás, a su vez ésta relación es dinámica ya que implica valores propios de una persona individual  conjuntamente a los de la sociedad en la que se encuentra. 
2. Es una rama de discusión y estudio filosófico, por ejemplo lo bueno y malo, que es justo, y cuál debe ser nuestra postura a determinados temas, etc. Podríamos decir que es una postura personal e íntima adoptada por cada quién según sus principios. 
3. Podemos encontrar la ética y su expresión en diferentes ambitos por ejemplo, existe la ética laboral en donde estos códigos contempla, reglas de cumplimiento obligatorio, para regular alguna determinada actividad profesional. 
4. Otro punto importante es destacar que la ética es constante, no suele cambiar con el tiempo, regula el comportamiento humano desde cada persona y desde su propia conciencia. Esto puede generar conflictos entre dos o más posturas éticas diferentes, conflicto entre moral y ética, por ejemplo temas como el aborto, condena de muerte, eutanasia, etc.

¿Qué es la Moral?:

Étimología del latín _MORIS_ (costumbre, principios y reglas que rigen en la vida social)

1. Es la práctica en sí de lo ético, en lo diario, lo cotidiano con respecto al desenvolvimiento de las personas en sus diferentes áreas, una personal moral es  cuando actúa de acuerdo a las normas costumbres y valores de su sociedad. Aunque estos pueden estar en contra de la ética de esa misma persona. 
2. Se refiere a los códigos de normas impuestos por una sociedad para regular la conducta o el comportamiento de los individuos. 
3. Abarca reglas tradiciones y valores compartidas por una sociedad en determinado momento de su historia. 
4. La moral tiende a ser normativa a reflejarse en reglamentos y prohibiciones,  aspectos de la dieta diaria y la higiene personal, como la prohibición total o parcial de consumir ciertos alimentos.
5. A diferencia de la Ética que es constante los códigos morales pueden variar en el tiempo y en el espacio.

**Comment by Gabrieltornier** [comment]
### **Ética Informática**

La ética en la informática se define como "como la disciplina que analiza los problemas éticos que son creados por la tecnología de los ordenadores o también los que son transformados o agravados por la misma". Es decir, por las personas que utilizan los avances de las tecnologías de la información.

### **La EI (Ética Informática) se plantea varios objetivos:**

Descubrir y articular dilemas éticos claves en informática.
Determinar en qué medida son agravados, transformados o creados por la tecnología informática.
Analizar y proponer un marco conceptual adecuado y formular principios de actuación para determinar qué hacer en las nuevas actividades ocasionadas por la informática en las que no se perciben con líneas de actuación de claridad.
Utilizar la teoría ética para aclarar los dilemas éticos y detectar errores en el razonamiento ético.
Proponer un marco conceptual adecuado para entender los dilemas éticos que originan el uso de la informática y además establecer una guía cuando no existe reglamentación de dar a Internet. Gracias a esto, las empresas han implementado guías y códigos de ética para mantener los más altos estándares de integridad, seguridad, comportamiento y conducta responsable. Como por ejemplo:
_Los diez mandamientos de la ética informática:_

1. No usarás una computadora para dañar a otros.
2. No interferirás con el trabajo ajeno.
3. No indagarás en los archivos ajenos.
4. No utilices una computadora para robar.
5. No conectes la informática para realizar fraudes.
6. No copiarás o ajustarás software que no hayas comprado.
7. No utilice los recursos informáticos ajenos sin la debida autorización.
8. No te apropiarás de los derechos intelectuales de otros.
9. Debes evaluar las consecuencias sociales de cualquier código que se desarrolle.
10. Siempre utilice las computadoras de manera de respetar los derechos de los demás.

**Comment by Gustaf02** [comment]
**Seguridad Informática:** 

La Seguridad Informática se refiere a las características y condiciones de los sistemas de procesamiento de datos y su almacenamiento, para garantizar su confidencialidad, integridad y disponibilidad.

Considerar aspectos de seguridad significa a) conocer el peligro, b) clasificarlo y c) protegerse de los impactos o daños de la mejor manera posible. Esto significa que solamente cuando estamos consientes de las potenciales amenazas, agresores y sus
intenciones dañinas (directas o indirectas) en contra de nosotros, podemos tomar medidas de protección adecuadas, para que no se pierda o dañe nuestros recursos valiosos.

En este sentido, la Seguridad Informática sirve para la protección de la información, en contra de amenazas o peligros, para evitar daños y para minimizar riesgos, relacionados con ella.

**Comment by Vane-SDev** [comment]
#  LOS CÓDIGOS ÉTICOS

"Los códigos de ética, tal como se conocen  en el mundo de las empresas, son sistemas de reglas establecidos con el propósito general de guiar el comportamiento de los integrantes de la organización y de aquellos con los cuales ésta actúa habitualmente: clientes, proveedores y  contratistas.  No  obstante  la  profesión  de  informática,  es  una  actividad  reconocida socialmente y así el futuro profesional informático, debe estar preparado para que un juez o una  empresa  le  solicite  un  dictamen  o  peritaje  informático  y  es  evidente  que  este  tipo  de informes, en la práctica, deben estar firmados por alguien con titulación superior, actuando con Probidad profesional, y obrando según ciencia y conciencia."

# LA ÉTICA EN INTERNET.  

Internet es el último y el más poderoso de una serie de medios de comunicación (telégrafo, ﻿teléfono,   radio   y   televisión)   que   durante   el   último   siglo   y   medio   ha   eliminado progresivamente el tiempo y el espacio como obstáculos para la comunicación entre un gran número de personas.
Como sucede con otros medios de comunicación, la persona y la comunidad de personas son el centro de la valoración ética de Internet. Con respecto al mensaje comunicado, al proceso de comunicación y a las cuestiones estructurales y sistemáticas de la comunicación. 
La cuestión ética consiste en saber si esto está contribuyendo al auténtico desarrollo humano y ayudando a las personas y a los pueblos a ser fieles a su destino trascendente.

>  "el principio ético fundamental es el siguiente: la persona humana y la comunidad humana son el fin y la medida del uso de los medios de comunicación social; la comunicación debería realizarse de persona a persona, con vistas al desarrollo integral de las mismas"

﻿
Internet tiene un conjunto de características impresionantes como lo describimos a continuación:
* Instantáneo.
* Inmediato.
* Mundial.
* Descentralizado.
* Interactivo

**Comment by JPAlvarezM** [comment]
### **Los problemas éticos más significativos en Internet.**
En gran medida el desarrollo científico y tecnológico de este siglo ha sido impulsado por
intereses vinculados con el afán de la hegemonía mundial de las grandes potencias, a las
exigencias del desarrollo industrial, así como a las pautas de consumo que se producen y se
difunden desde las sociedades que han marcado la avanzada en los procesos de
modernización. Por eso los estados y las grandes empresas transnacionales se encuentran
entre los mayores protagonistas de la ciencia y la tecnología.
Una enumeración somera de los problemas éticos del ciberespacio nos ofrece la siguiente
lista.

- **La privacidad:** no tanto la posibilidad (real) de fallos en los sistemas de correo que provoquen mensajes que van a lugares equivocados, si no más bien la intromisión intencional. Esta intromisión puede ser desde la del compañero del trabajo que lee nuestro trabajo hasta el sistemático intervencionismo estatal.
- **La Identidad:** es posible esconder la verdadera identidad a la hora de intervenir en una conversación.
-  **La Inversa**: la capacidad de manipulación se traslada de los mecanismos habituales a la sociedad (como la posición social económica) a las habilidades de aquellos que manejan mas el medio o que pueden intervenir de manera subrepticia en las comunicaciones ajenas.
