### ISSUE TITLE
Actividad individual a realizar por todos los integrantes: Carga de CV 

### ISSUE THREAD

**Issue by Gabrieltornier** [SofiaEJac/Grupo5A17_Programador2022#7]
Se adjunta y crea CV de cada miembro del equipo.

**Comment by SofiaEJac** [comment]
[https://drive.google.com/file/d/1GUTRbYxs5KEE23Dv3T4NshUSVwT1TMaQ/view](url)
Instructivo para subir los CV desde la rama personal al repositorio remoto

**Comment by SofiaEJac** [comment]
## Instructivo para subir el CV desde la rama personal de Git al repositorio remoto:
https://drive.google.com/file/d/1GUTRbYxs5KEE23Dv3T4NshUSVwT1TMaQ/view
