### ISSUE TITLE
Conceptos de Python

### ISSUE THREAD

**Issue by Gabrieltornier** [SofiaEJac/Grupo5A17_Programador2022#9]
¿Que es Python? ¿Cuáles son sus principales características?

**Comment by SofiaEJac** [comment]
# Función Print:
 **La función print() es una función integrada imprime/envía un mensaje específico a la pantalla/ventana de consola. 
 Las funciones integradas, al contrario de las funciones definidas por el usuario, están siempre disponibles y no tienen que ser importadas.
 Para llamar a una función (invocación de función), debe utilizarse el nombre de la función seguido de un paréntesis. Puedes pasar argumentos a una función colocándolos dentro de los paréntesis. Se Deben separar los argumentos con una coma, por ejemplo, print("¡Hola,", "Mundo!"). una función print() "vacía" imprime una línea vacía a la pantalla.**

Una función puede tener:
* Un efecto
* Un resultado
* Un argumento

_¿Cuál es el efecto de la función print?_

- Toma los argumentos (puede aceptar más de un argumento y también puede aceptar menos de un argumento).
- Los convierte en un formato legible para el ser humano si es necesario (como puedes sospechar, las cadenas no requieren esta acción, ya que la cadena ya es legible).
- Envía los datos resultantes al dispositivo de salida (generalmente la consola); en otras palabras, cualquier cosa que se ponga en la función de print() aparecerá en la pantalla.

**Comment by SofiaEJac** [comment]
# **¿Qué es Python?**

**Python** es un lenguaje de programación de **alto nivel**, **interpretado**, orientado a objetos y de uso generalizado con semántica dinámica, que se utiliza para la programación de propósito general.

**Comment by Vane-SDev** [comment]
# Operadores en Python
Los operadores son símbolos que le indican al intérprete que realice una operación específica, como aritmética, comparación, lógica, etc.
Algunos de los diferentes tipos de operadores en Python son: 

### - Operadores aritméticos
Un operador aritmético toma dos operandos como entrada, realiza un cálculo y devuelve el resultado.

Considera la expresión, “a = 2 + 3”. Aquí, 2 y  3 son los operandos y  + es el operador aritmético. El resultado de la operación se almacena en la variable a.
![image](https://user-images.githubusercontent.com/106666059/177664190-25314ce7-ab9c-4105-8275-e09f6ea7f4a1.png)


### - Operadores relacionales
Un operador relacional se emplea para comparar y establecer la relación entre ellos. Devuelve un valor booleano (true o false) basado en la condición.
![image](https://user-images.githubusercontent.com/106666059/177663539-13dcf779-4b15-456d-9971-0147ebf387a9.png)

### - Operadores Bit a Bit
Un operador bit a bit realiza operaciones en los operandos bit a bit.

 ![image](https://user-images.githubusercontent.com/106666059/177663648-3da16678-76c3-4d81-be4d-58207bf7ea76.png)

### - Operadores de asignación
Se utiliza un operador de asignación para asignar valores a una variable. Esto generalmente se combina con otros operadores (como aritmética, bit a bit) donde la operación se realiza en los operandos y el resultado se asigna al operando izquierdo.

Considera los siguientes ejemplos,

a = 18. Aquí = es un operador de asignación, y el resultado se almacena en la variable a.

a + = 10. Aquí += es un operador de asignación, y el resultado se almacena en la variable a. Es lo mismo que a = a + 10.
![image](https://user-images.githubusercontent.com/106666059/177664106-fcc7eafa-bcc9-4c08-a4b5-4c1587e74013.png)


### - Operadores lógicos
Se utiliza un operador lógico para tomar una decisión basada en múltiples condiciones. Los operadores lógicos utilizados en Python son  and, or y not.
![image](https://user-images.githubusercontent.com/106666059/177664270-3575dc0f-9b8c-4846-a345-64db5ca6ab1c.png)

**Comment by lacman92** [comment]
La función **print()**

Observa la línea de código a continuación:

print("¡Hola, Mundo!")


La palabra print que puedes ver aquí es el nombre de una función. Eso no significa que dondequiera que aparezca esta palabra, será siempre el nombre de una función. El significado de la palabra proviene del contexto en el cual se haya utilizado la palabra.

Probablemente hayas encontrado el término función muchas veces antes, durante las clases de matemáticas. Probablemente también puedes recordar varios nombres de funciones matemáticas, como seno o logaritmo.

Las funciones de Python, sin embargo, son más flexibles y pueden contener más que sus parientes matemáticos.

Una función (en este contexto) es una parte separada del código de computadora el cual es capaz de:

Causar algún efecto (por ejemplo, enviar texto a la terminal, crear un archivo, dibujar una imagen, reproducir un sonido, etc.); esto es algo completamente inaudito en el mundo de las matemáticas.
Evaluar un valor (por ejemplo, la raíz cuadrada de un valor o la longitud de un texto dado) y devolverlo como el resultado de la función; esto es lo que hace que las funciones de Python sean parientes de los conceptos matemáticos.
Además, muchas de las funciones de Python pueden hacer las dos cosas anteriores juntas.


¿De dónde provienen las funciones?

Pueden venir de Python mismo. La función print es una de este tipo; dicha función es un valor agregado de Python junto con su entorno (está integrada); no tienes que hacer nada especial (por ejemplo, pedirle a alguien algo) si quieres usarla.
Pueden provenir de uno o varios de los módulos de Python llamados complementos; algunos de los módulos vienen con Python, otros pueden requerir una instalación por separado, cual sea el caso, todos deben estar conectados explícitamente con el código (te mostraremos cómo hacer esto pronto).
Puedes escribirlas tú mismo, colocando tantas funciones como desees y necesites dentro de su programa para hacerlo más simple, claro y elegante.
El nombre de la función debe ser significativo (el nombre de la función print es evidente), imprime en la terminal.

**Comment by JPAlvarezM** [comment]
### **Función Input:**
Los programas se hacen para tener interacción con el usuario. Una de las formas de
interacción es solicitar la entrada de datos por teclado. Como muchos otros lenguajes de
programación, Python también nos ofrece la posibilidad de leer la información introducida
por teclado. Para ello se utiliza la función **input()**
La función **input()** siempre nos devuelve un objeto de tipo cadena de texto o **str.**
Tenerlo muy en cuenta a la hora de trabajar con números, ya que debemos realizar una
conversión explícita si queremos trabajar con los valores ingresados, utilizando los operadores arriba detallados.
